name: LLM Editor

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: write
  
jobs:
  llm_editor_job:
    # Only run if the label attached is "prompt"
    if: ${{ github.event.label.name == 'prompt' }}
    runs-on: ubuntu-latest

    # Concurrency prevents race conditions by grouping workflow runs together.
    concurrency:
      group: LLM-Editor-${{ github.repository }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install google-genai beautifulsoup4

      - name: Run LLM Editor Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python llm_editor.py
